module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: ['**/test/integration/**/*.integration.test.ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@dtos/(.*)$': '<rootDir>/src/dtos/$1',
    '^@errors/(.*)$': '<rootDir>/src/errors/$1',
    '^@exceptions/(.*)$': '<rootDir>/src/exceptions/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@interfaces/(.*)$': '<rootDir>/src/interfaces/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@queries/(.*)$': '<rootDir>/src/queries/$1',
    '^@validations/(.*)$': '<rootDir>/src/validations/$1',
  },
  setupFiles: ['<rootDir>/src/test/integration/env-setup.ts'],
  setupFilesAfterEnv: ['<rootDir>/src/test/integration/setup.ts'],
  maxWorkers: 1,
  testTimeout: 15000,
};
